# Simplilearn Project

Importing train and test data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv(r'D:\Simplilearn\ML\Project submission\train\train.csv')

In [3]:
test_data = pd.read_csv(r'D:\Simplilearn\ML\Project submission\test\test.csv')

In [4]:
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [5]:
test_data.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

Getting info about the dataset.

In [6]:
train_data.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Dropping the Id column from the dataset.

In [7]:
train_data.drop('ID',axis=1,inplace=True)

In [8]:
test_data.drop('ID',axis=1,inplace=True)

In [9]:
train_data.head()

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,130.81,k,v,at,a,d,u,j,o,0,...,0,0,1,0,0,0,0,0,0,0
1,88.53,k,t,av,e,d,y,l,o,0,...,1,0,0,0,0,0,0,0,0,0
2,76.26,az,w,n,c,d,x,j,x,0,...,0,0,0,0,0,0,1,0,0,0
3,80.62,az,t,n,f,d,x,l,e,0,...,0,0,0,0,0,0,0,0,0,0
4,78.02,az,v,n,f,d,h,d,n,0,...,0,0,0,0,0,0,0,0,0,0

Splitting independent variable form the train data.

In [10]:
x_pred = train_data['y']

In [11]:
train_data.drop('y',axis=1,inplace=True)

In [12]:
train_data.shape

(4209, 376)

In [13]:
train_data.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,k,v,at,a,d,u,j,o,0,0,...,0,0,1,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,o,0,0,...,1,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,x,0,0,...,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,e,0,0,...,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,d,n,0,0,...,0,0,0,0,0,0,0,0,0,0

Action-1: Finding the variance of the independent variable.

In [14]:
variance = train_data.var()

In [15]:
variance

X10     0.013131
X11     0.000000
X12     0.069457
X13     0.054623
X14     0.244893
X15     0.000475
X16     0.002607
X17     0.007547
X18     0.007781
X19     0.089660
X20     0.122430
X21     0.002607
X22     0.079414
X23     0.020248
X24     0.001898
X26     0.004966
X27     0.216714
X28     0.031497
X29     0.041164
X30     0.004495
X31     0.178411
X32     0.011044
X33     0.000238
X34     0.005436
X35     0.178411
X36     0.004495
X37     0.178411
X38     0.032163
X39     0.000238
X40     0.000712
          ...
X355    0.235746
X356    0.147541
X357    0.001187
X358    0.244721
X359    0.030830
X360    0.070667
X361    0.032828
X362    0.249647
X363    0.185599
X364    0.002844
X365    0.002844
X366    0.001187
X367    0.049123
X368    0.058803
X369    0.000475
X370    0.006610
X371    0.014055
X372    0.000475
X373    0.018879
X374    0.175715
X375    0.217233
X376    0.053993
X377    0.215753
X378    0.020248
X379    0.009415
X380    0.008015
X382    0.007547
X383    0.001661
X384    0.000475
X385    0.001424
Length: 368, dtype: float64

In [16]:
variance[variance == 0]

X11     0.0
X93     0.0
X107    0.0
X233    0.0
X235    0.0
X268    0.0
X289    0.0
X290    0.0
X293    0.0
X297    0.0
X330    0.0
X347    0.0
dtype: float64

Above is the column names having variance zero.
We will drop these columns from our dataset.

In [17]:
drop_col = ['X11','X93','X107','X233','X235','X268','X289','X290','X293','X297','X330','X347']

In [18]:
train_data.drop(drop_col,axis=1,inplace=True)

In [19]:
train_data.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,k,v,at,a,d,u,j,o,0,0,...,0,0,1,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,o,0,0,...,1,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,x,0,0,...,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,e,0,0,...,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,d,n,0,0,...,0,0,0,0,0,0,0,0,0,0

Similarly, we will remove the zero variance columns from the test data.

In [20]:
test_data.drop(drop_col,axis=1,inplace=True)

In [21]:
test_data.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,az,v,n,f,d,t,a,w,0,0,...,0,0,0,1,0,0,0,0,0,0
1,t,b,ai,a,d,b,g,y,0,0,...,0,0,1,0,0,0,0,0,0,0
2,az,v,as,f,d,a,j,j,0,0,...,0,0,0,1,0,0,0,0,0,0
3,az,l,n,f,d,z,l,n,0,0,...,0,0,0,1,0,0,0,0,0,0
4,w,s,as,c,d,y,i,m,0,0,...,1,0,0,0,0,0,0,0,0,0

Action 2: Checking for null and unique values in train and test dataset.

Now, we will set pandas to see all the rows.Don't hide any

In [22]:
pd.set_option('display.max_rows',None)

In [23]:
train_data.isnull().sum()

X0      0
X1      0
X2      0
X3      0
X4      0
X5      0
X6      0
X8      0
X10     0
X12     0
X13     0
X14     0
X15     0
X16     0
X17     0
X18     0
X19     0
X20     0
X21     0
X22     0
X23     0
X24     0
X26     0
X27     0
X28     0
X29     0
X30     0
X31     0
X32     0
X33     0
X34     0
X35     0
X36     0
X37     0
X38     0
X39     0
X40     0
X41     0
X42     0
X43     0
X44     0
X45     0
X46     0
X47     0
X48     0
X49     0
X50     0
X51     0
X52     0
X53     0
X54     0
X55     0
X56     0
X57     0
X58     0
X59     0
X60     0
X61     0
X62     0
X63     0
X64     0
X65     0
X66     0
X67     0
X68     0
X69     0
X70     0
X71     0
X73     0
X74     0
X75     0
X76     0
X77     0
X78     0
X79     0
X80     0
X81     0
X82     0
X83     0
X84     0
X85     0
X86     0
X87     0
X88     0
X89     0
X90     0
X91     0
X92     0
X94     0
X95     0
X96     0
X97     0
X98     0
X99     0
X100    0
X101    0
X102    0
X103    0
X104    0
X105    0
X106    0
X108    0
X109    0
X110    0
X111    0
X112    0
X113    0
X114    0
X115    0
X116    0
X117    0
X118    0
X119    0
X120    0
X122    0
X123    0
X124    0
X125    0
X126    0
X127    0
X128    0
X129    0
X130    0
X131    0
X132    0
X133    0
X134    0
X135    0
X136    0
X137    0
X138    0
X139    0
X140    0
X141    0
X142    0
X143    0
X144    0
X145    0
X146    0
X147    0
X148    0
X150    0
X151    0
X152    0
X153    0
X154    0
X155    0
X156    0
X157    0
X158    0
X159    0
X160    0
X161    0
X162    0
X163    0
X164    0
X165    0
X166    0
X167    0
X168    0
X169    0
X170    0
X171    0
X172    0
X173    0
X174    0
X175    0
X176    0
X177    0
X178    0
X179    0
X180    0
X181    0
X182    0
X183    0
X184    0
X185    0
X186    0
X187    0
X189    0
X190    0
X191    0
X192    0
X194    0
X195    0
X196    0
X197    0
X198    0
X199    0
X200    0
X201    0
X202    0
X203    0
X204    0
X205    0
X206    0
X207    0
X208    0
X209    0
X210    0
X211    0
X212    0
X213    0
X214    0
X215    0
X216    0
X217    0
X218    0
X219    0
X220    0
X221    0
X222    0
X223    0
X224    0
X225    0
X226    0
X227    0
X228    0
X229    0
X230    0
X231    0
X232    0
X234    0
X236    0
X237    0
X238    0
X239    0
X240    0
X241    0
X242    0
X243    0
X244    0
X245    0
X246    0
X247    0
X248    0
X249    0
X250    0
X251    0
X252    0
X253    0
X254    0
X255    0
X256    0
X257    0
X258    0
X259    0
X260    0
X261    0
X262    0
X263    0
X264    0
X265    0
X266    0
X267    0
X269    0
X270    0
X271    0
X272    0
X273    0
X274    0
X275    0
X276    0
X277    0
X278    0
X279    0
X280    0
X281    0
X282    0
X283    0
X284    0
X285    0
X286    0
X287    0
X288    0
X291    0
X292    0
X294    0
X295    0
X296    0
X298    0
X299    0
X300    0
X301    0
X302    0
X304    0
X305    0
X306    0
X307    0
X308    0
X309    0
X310    0
X311    0
X312    0
X313    0
X314    0
X315    0
X316    0
X317    0
X318    0
X319    0
X320    0
X321    0
X322    0
X323    0
X324    0
X325    0
X326    0
X327    0
X328    0
X329    0
X331    0
X332    0
X333    0
X334    0
X335    0
X336    0
X337    0
X338    0
X339    0
X340    0
X341    0
X342    0
X343    0
X344    0
X345    0
X346    0
X348    0
X349    0
X350    0
X351    0
X352    0
X353    0
X354    0
X355    0
X356    0
X357    0
X358    0
X359    0
X360    0
X361    0
X362    0
X363    0
X364    0
X365    0
X366    0
X367    0
X368    0
X369    0
X370    0
X371    0
X372    0
X373    0
X374    0
X375    0
X376    0
X377    0
X378    0
X379    0
X380    0
X382    0
X383    0
X384    0
X385    0
dtype: int64

Checking for null data present in test dataset.

In [24]:
test_data.isnull().sum()

X0      0
X1      0
X2      0
X3      0
X4      0
X5      0
X6      0
X8      0
X10     0
X12     0
X13     0
X14     0
X15     0
X16     0
X17     0
X18     0
X19     0
X20     0
X21     0
X22     0
X23     0
X24     0
X26     0
X27     0
X28     0
X29     0
X30     0
X31     0
X32     0
X33     0
X34     0
X35     0
X36     0
X37     0
X38     0
X39     0
X40     0
X41     0
X42     0
X43     0
X44     0
X45     0
X46     0
X47     0
X48     0
X49     0
X50     0
X51     0
X52     0
X53     0
X54     0
X55     0
X56     0
X57     0
X58     0
X59     0
X60     0
X61     0
X62     0
X63     0
X64     0
X65     0
X66     0
X67     0
X68     0
X69     0
X70     0
X71     0
X73     0
X74     0
X75     0
X76     0
X77     0
X78     0
X79     0
X80     0
X81     0
X82     0
X83     0
X84     0
X85     0
X86     0
X87     0
X88     0
X89     0
X90     0
X91     0
X92     0
X94     0
X95     0
X96     0
X97     0
X98     0
X99     0
X100    0
X101    0
X102    0
X103    0
X104    0
X105    0
X106    0
X108    0
X109    0
X110    0
X111    0
X112    0
X113    0
X114    0
X115    0
X116    0
X117    0
X118    0
X119    0
X120    0
X122    0
X123    0
X124    0
X125    0
X126    0
X127    0
X128    0
X129    0
X130    0
X131    0
X132    0
X133    0
X134    0
X135    0
X136    0
X137    0
X138    0
X139    0
X140    0
X141    0
X142    0
X143    0
X144    0
X145    0
X146    0
X147    0
X148    0
X150    0
X151    0
X152    0
X153    0
X154    0
X155    0
X156    0
X157    0
X158    0
X159    0
X160    0
X161    0
X162    0
X163    0
X164    0
X165    0
X166    0
X167    0
X168    0
X169    0
X170    0
X171    0
X172    0
X173    0
X174    0
X175    0
X176    0
X177    0
X178    0
X179    0
X180    0
X181    0
X182    0
X183    0
X184    0
X185    0
X186    0
X187    0
X189    0
X190    0
X191    0
X192    0
X194    0
X195    0
X196    0
X197    0
X198    0
X199    0
X200    0
X201    0
X202    0
X203    0
X204    0
X205    0
X206    0
X207    0
X208    0
X209    0
X210    0
X211    0
X212    0
X213    0
X214    0
X215    0
X216    0
X217    0
X218    0
X219    0
X220    0
X221    0
X222    0
X223    0
X224    0
X225    0
X226    0
X227    0
X228    0
X229    0
X230    0
X231    0
X232    0
X234    0
X236    0
X237    0
X238    0
X239    0
X240    0
X241    0
X242    0
X243    0
X244    0
X245    0
X246    0
X247    0
X248    0
X249    0
X250    0
X251    0
X252    0
X253    0
X254    0
X255    0
X256    0
X257    0
X258    0
X259    0
X260    0
X261    0
X262    0
X263    0
X264    0
X265    0
X266    0
X267    0
X269    0
X270    0
X271    0
X272    0
X273    0
X274    0
X275    0
X276    0
X277    0
X278    0
X279    0
X280    0
X281    0
X282    0
X283    0
X284    0
X285    0
X286    0
X287    0
X288    0
X291    0
X292    0
X294    0
X295    0
X296    0
X298    0
X299    0
X300    0
X301    0
X302    0
X304    0
X305    0
X306    0
X307    0
X308    0
X309    0
X310    0
X311    0
X312    0
X313    0
X314    0
X315    0
X316    0
X317    0
X318    0
X319    0
X320    0
X321    0
X322    0
X323    0
X324    0
X325    0
X326    0
X327    0
X328    0
X329    0
X331    0
X332    0
X333    0
X334    0
X335    0
X336    0
X337    0
X338    0
X339    0
X340    0
X341    0
X342    0
X343    0
X344    0
X345    0
X346    0
X348    0
X349    0
X350    0
X351    0
X352    0
X353    0
X354    0
X355    0
X356    0
X357    0
X358    0
X359    0
X360    0
X361    0
X362    0
X363    0
X364    0
X365    0
X366    0
X367    0
X368    0
X369    0
X370    0
X371    0
X372    0
X373    0
X374    0
X375    0
X376    0
X377    0
X378    0
X379    0
X380    0
X382    0
X383    0
X384    0
X385    0
dtype: int64

As, we can see there are no null values present in any columns of train and test data.
Now, lets check for the count of unique values present in train and test data.

In [25]:
train_data.nunique()

X0      47
X1      27
X2      44
X3       7
X4       4
X5      29
X6      12
X8      25
X10      2
X12      2
X13      2
X14      2
X15      2
X16      2
X17      2
X18      2
X19      2
X20      2
X21      2
X22      2
X23      2
X24      2
X26      2
X27      2
X28      2
X29      2
X30      2
X31      2
X32      2
X33      2
X34      2
X35      2
X36      2
X37      2
X38      2
X39      2
X40      2
X41      2
X42      2
X43      2
X44      2
X45      2
X46      2
X47      2
X48      2
X49      2
X50      2
X51      2
X52      2
X53      2
X54      2
X55      2
X56      2
X57      2
X58      2
X59      2
X60      2
X61      2
X62      2
X63      2
X64      2
X65      2
X66      2
X67      2
X68      2
X69      2
X70      2
X71      2
X73      2
X74      2
X75      2
X76      2
X77      2
X78      2
X79      2
X80      2
X81      2
X82      2
X83      2
X84      2
X85      2
X86      2
X87      2
X88      2
X89      2
X90      2
X91      2
X92      2
X94      2
X95      2
X96      2
X97      2
X98      2
X99      2
X100     2
X101     2
X102     2
X103     2
X104     2
X105     2
X106     2
X108     2
X109     2
X110     2
X111     2
X112     2
X113     2
X114     2
X115     2
X116     2
X117     2
X118     2
X119     2
X120     2
X122     2
X123     2
X124     2
X125     2
X126     2
X127     2
X128     2
X129     2
X130     2
X131     2
X132     2
X133     2
X134     2
X135     2
X136     2
X137     2
X138     2
X139     2
X140     2
X141     2
X142     2
X143     2
X144     2
X145     2
X146     2
X147     2
X148     2
X150     2
X151     2
X152     2
X153     2
X154     2
X155     2
X156     2
X157     2
X158     2
X159     2
X160     2
X161     2
X162     2
X163     2
X164     2
X165     2
X166     2
X167     2
X168     2
X169     2
X170     2
X171     2
X172     2
X173     2
X174     2
X175     2
X176     2
X177     2
X178     2
X179     2
X180     2
X181     2
X182     2
X183     2
X184     2
X185     2
X186     2
X187     2
X189     2
X190     2
X191     2
X192     2
X194     2
X195     2
X196     2
X197     2
X198     2
X199     2
X200     2
X201     2
X202     2
X203     2
X204     2
X205     2
X206     2
X207     2
X208     2
X209     2
X210     2
X211     2
X212     2
X213     2
X214     2
X215     2
X216     2
X217     2
X218     2
X219     2
X220     2
X221     2
X222     2
X223     2
X224     2
X225     2
X226     2
X227     2
X228     2
X229     2
X230     2
X231     2
X232     2
X234     2
X236     2
X237     2
X238     2
X239     2
X240     2
X241     2
X242     2
X243     2
X244     2
X245     2
X246     2
X247     2
X248     2
X249     2
X250     2
X251     2
X252     2
X253     2
X254     2
X255     2
X256     2
X257     2
X258     2
X259     2
X260     2
X261     2
X262     2
X263     2
X264     2
X265     2
X266     2
X267     2
X269     2
X270     2
X271     2
X272     2
X273     2
X274     2
X275     2
X276     2
X277     2
X278     2
X279     2
X280     2
X281     2
X282     2
X283     2
X284     2
X285     2
X286     2
X287     2
X288     2
X291     2
X292     2
X294     2
X295     2
X296     2
X298     2
X299     2
X300     2
X301     2
X302     2
X304     2
X305     2
X306     2
X307     2
X308     2
X309     2
X310     2
X311     2
X312     2
X313     2
X314     2
X315     2
X316     2
X317     2
X318     2
X319     2
X320     2
X321     2
X322     2
X323     2
X324     2
X325     2
X326     2
X327     2
X328     2
X329     2
X331     2
X332     2
X333     2
X334     2
X335     2
X336     2
X337     2
X338     2
X339     2
X340     2
X341     2
X342     2
X343     2
X344     2
X345     2
X346     2
X348     2
X349     2
X350     2
X351     2
X352     2
X353     2
X354     2
X355     2
X356     2
X357     2
X358     2
X359     2
X360     2
X361     2
X362     2
X363     2
X364     2
X365     2
X366     2
X367     2
X368     2
X369     2
X370     2
X371     2
X372     2
X373     2
X374     2
X375     2
X376     2
X377     2
X378     2
X379     2
X380     2
X382     2
X383     2
X384     2
X385     2
dtype: int64

In [26]:
test_data.nunique()

X0      49
X1      27
X2      45
X3       7
X4       4
X5      32
X6      12
X8      25
X10      2
X12      2
X13      2
X14      2
X15      2
X16      2
X17      2
X18      2
X19      2
X20      2
X21      2
X22      2
X23      2
X24      2
X26      2
X27      2
X28      2
X29      2
X30      2
X31      2
X32      2
X33      2
X34      2
X35      2
X36      2
X37      2
X38      2
X39      2
X40      2
X41      2
X42      2
X43      2
X44      2
X45      2
X46      2
X47      2
X48      2
X49      2
X50      2
X51      2
X52      2
X53      2
X54      2
X55      2
X56      2
X57      2
X58      2
X59      2
X60      2
X61      2
X62      2
X63      2
X64      2
X65      2
X66      2
X67      2
X68      2
X69      2
X70      2
X71      2
X73      2
X74      2
X75      2
X76      2
X77      2
X78      2
X79      2
X80      2
X81      2
X82      2
X83      2
X84      2
X85      2
X86      2
X87      2
X88      2
X89      2
X90      2
X91      2
X92      2
X94      2
X95      2
X96      2
X97      2
X98      2
X99      2
X100     2
X101     2
X102     2
X103     2
X104     2
X105     2
X106     2
X108     2
X109     2
X110     2
X111     2
X112     2
X113     2
X114     2
X115     2
X116     2
X117     2
X118     2
X119     2
X120     2
X122     2
X123     2
X124     2
X125     2
X126     2
X127     2
X128     2
X129     2
X130     2
X131     2
X132     2
X133     2
X134     2
X135     2
X136     2
X137     2
X138     2
X139     2
X140     2
X141     2
X142     2
X143     2
X144     2
X145     2
X146     2
X147     2
X148     2
X150     2
X151     2
X152     2
X153     2
X154     2
X155     2
X156     2
X157     2
X158     2
X159     2
X160     2
X161     2
X162     2
X163     2
X164     2
X165     2
X166     2
X167     2
X168     2
X169     2
X170     2
X171     2
X172     2
X173     2
X174     2
X175     2
X176     2
X177     2
X178     2
X179     2
X180     2
X181     2
X182     2
X183     2
X184     2
X185     2
X186     2
X187     2
X189     2
X190     2
X191     2
X192     2
X194     2
X195     2
X196     2
X197     2
X198     2
X199     2
X200     2
X201     2
X202     2
X203     2
X204     2
X205     2
X206     2
X207     2
X208     2
X209     2
X210     2
X211     2
X212     2
X213     2
X214     2
X215     2
X216     2
X217     2
X218     2
X219     2
X220     2
X221     2
X222     2
X223     2
X224     2
X225     2
X226     2
X227     2
X228     2
X229     2
X230     2
X231     2
X232     2
X234     2
X236     2
X237     2
X238     2
X239     2
X240     2
X241     2
X242     2
X243     2
X244     2
X245     2
X246     2
X247     2
X248     2
X249     2
X250     2
X251     2
X252     2
X253     2
X254     2
X255     2
X256     2
X257     1
X258     1
X259     2
X260     2
X261     2
X262     2
X263     2
X264     2
X265     2
X266     2
X267     2
X269     2
X270     2
X271     2
X272     2
X273     2
X274     2
X275     2
X276     2
X277     2
X278     2
X279     2
X280     2
X281     2
X282     2
X283     2
X284     2
X285     2
X286     2
X287     2
X288     2
X291     2
X292     2
X294     2
X295     1
X296     1
X298     2
X299     2
X300     2
X301     2
X302     2
X304     2
X305     2
X306     2
X307     2
X308     2
X309     2
X310     2
X311     2
X312     2
X313     2
X314     2
X315     2
X316     2
X317     2
X318     2
X319     2
X320     2
X321     2
X322     2
X323     2
X324     2
X325     2
X326     2
X327     2
X328     2
X329     2
X331     2
X332     2
X333     2
X334     2
X335     2
X336     2
X337     2
X338     2
X339     2
X340     2
X341     2
X342     2
X343     2
X344     2
X345     2
X346     2
X348     2
X349     2
X350     2
X351     2
X352     2
X353     2
X354     2
X355     2
X356     2
X357     2
X358     2
X359     2
X360     2
X361     2
X362     2
X363     2
X364     2
X365     2
X366     2
X367     2
X368     2
X369     1
X370     2
X371     2
X372     2
X373     2
X374     2
X375     2
X376     2
X377     2
X378     2
X379     2
X380     2
X382     2
X383     2
X384     2
X385     2
dtype: int64

Action 3: Applying lable encoder to the train and test dataset to convert the categorical variable into numeric form.

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
encoder = LabelEncoder()

In [29]:
for col in train_data.iloc[:,0:8]:
    train_data[col] = encoder.fit_transform(train_data[col])

In [30]:
train_data.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,32,23,17,0,3,24,9,14,0,0,...,0,0,1,0,0,0,0,0,0,0
1,32,21,19,4,3,28,11,14,0,0,...,1,0,0,0,0,0,0,0,0,0
2,20,24,34,2,3,27,9,23,0,0,...,0,0,0,0,0,0,1,0,0,0
3,20,21,34,5,3,27,11,4,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20,23,34,5,3,12,3,13,0,0,...,0,0,0,0,0,0,0,0,0,0

Now, label encoding the test data.

In [31]:
for col in test_data.iloc[:,0:8]:
    test_data[col] = encoder.fit_transform(test_data[col])

In [32]:
test_data.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,21,23,34,5,3,26,0,22,0,0,...,0,0,0,1,0,0,0,0,0,0
1,42,3,8,0,3,9,6,24,0,0,...,0,0,1,0,0,0,0,0,0,0
2,21,23,17,5,3,0,9,9,0,0,...,0,0,0,1,0,0,0,0,0,0
3,21,13,34,5,3,31,11,13,0,0,...,0,0,0,1,0,0,0,0,0,0
4,45,20,17,2,3,30,8,12,0,0,...,1,0,0,0,0,0,0,0,0,0

Action 4: Applying dimensionality reduction on train and test dataset using Principle component             analysis.

Standardizing the data.

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_data = sc.fit_transform(train_data)
test_data = sc.transform(test_data)

C:\Users\91904\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\91904\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\91904\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.

In [34]:
from sklearn.decomposition import PCA
pca = PCA(n_components= None)

In [35]:
train_data = pca.fit_transform(train_data)

In [36]:
test_data = pca.transform(test_data)

In [37]:
(pca.explained_variance_ratio_)

array([6.89266892e-02, 5.68841213e-02, 4.53745695e-02, 3.42677135e-02,
       3.26430877e-02, 3.16266067e-02, 2.86252442e-02, 2.12375123e-02,
       1.97041337e-02, 1.78319550e-02, 1.64006646e-02, 1.56428622e-02,
       1.46274226e-02, 1.44833491e-02, 1.34828580e-02, 1.29516175e-02,
       1.24383219e-02, 1.17310333e-02, 1.12105051e-02, 1.07727793e-02,
       9.92512898e-03, 9.69449157e-03, 9.42523076e-03, 9.09867975e-03,
       8.74223908e-03, 8.43069482e-03, 7.90204943e-03, 7.63217614e-03,
       7.33541876e-03, 7.14905572e-03, 6.92957269e-03, 6.76677298e-03,
       6.52534438e-03, 6.41494089e-03, 6.22692040e-03, 5.99196153e-03,
       5.88086185e-03, 5.74693562e-03, 5.63702738e-03, 5.53409616e-03,
       5.50641149e-03, 5.40082599e-03, 5.33910600e-03, 5.24611598e-03,
       5.10194247e-03, 5.03232420e-03, 4.95885463e-03, 4.72691565e-03,
       4.64475228e-03, 4.56521484e-03, 4.39624472e-03, 4.32947533e-03,
       4.30322432e-03, 4.23762131e-03, 4.20211958e-03, 4.15473420e-03,
       4.06699537e-03, 4.03462750e-03, 3.91873995e-03, 3.88747084e-03,
       3.81759321e-03, 3.75560105e-03, 3.72440051e-03, 3.65910562e-03,
       3.59566547e-03, 3.55229656e-03, 3.49700953e-03, 3.46182278e-03,
       3.40471717e-03, 3.34157815e-03, 3.30984908e-03, 3.25521932e-03,
       3.24084510e-03, 3.21045090e-03, 3.16671200e-03, 3.16169105e-03,
       3.09963730e-03, 3.07579140e-03, 3.05317642e-03, 3.03955238e-03,
       3.00255847e-03, 2.98903148e-03, 2.95834824e-03, 2.92906873e-03,
       2.90789282e-03, 2.89246840e-03, 2.87088871e-03, 2.84861071e-03,
       2.82893540e-03, 2.80661865e-03, 2.79489424e-03, 2.76964748e-03,
       2.74977677e-03, 2.72538185e-03, 2.72396743e-03, 2.66915947e-03,
       2.64849773e-03, 2.63035478e-03, 2.60995440e-03, 2.60665425e-03,
       2.57383600e-03, 2.54968974e-03, 2.53621249e-03, 2.51953928e-03,
       2.50398175e-03, 2.48457976e-03, 2.44053200e-03, 2.42183601e-03,
       2.40353580e-03, 2.38432335e-03, 2.34517965e-03, 2.31166118e-03,
       2.30049772e-03, 2.27223313e-03, 2.25613123e-03, 2.23532575e-03,
       2.21465563e-03, 2.20028258e-03, 2.15055308e-03, 2.13667795e-03,
       2.10335610e-03, 2.09410362e-03, 2.05842058e-03, 2.04122098e-03,
       2.02468809e-03, 1.98912003e-03, 1.93876262e-03, 1.91967571e-03,
       1.91801301e-03, 1.87935329e-03, 1.85171337e-03, 1.81419321e-03,
       1.79357485e-03, 1.78621289e-03, 1.75392321e-03, 1.71752943e-03,
       1.70719881e-03, 1.67983148e-03, 1.65808186e-03, 1.61860975e-03,
       1.61139410e-03, 1.57706719e-03, 1.54261681e-03, 1.53538284e-03,
       1.49678823e-03, 1.49384890e-03, 1.47852266e-03, 1.42828100e-03,
       1.41108081e-03, 1.37376476e-03, 1.33814992e-03, 1.28803283e-03,
       1.26972355e-03, 1.26213163e-03, 1.20721187e-03, 1.16191771e-03,
       1.14336841e-03, 1.12752230e-03, 1.09498612e-03, 1.05869705e-03,
       9.99910624e-04, 9.89110199e-04, 9.86361463e-04, 9.54546927e-04,
       9.45056062e-04, 9.11514885e-04, 8.99355342e-04, 8.80886749e-04,
       8.63653466e-04, 8.59439761e-04, 8.29410991e-04, 8.24059997e-04,
       7.98201807e-04, 7.91126650e-04, 7.78713087e-04, 7.44845247e-04,
       7.24330743e-04, 7.08041140e-04, 6.85829934e-04, 6.72145117e-04,
       6.55718352e-04, 6.40733883e-04, 6.12000447e-04, 5.86075445e-04,
       5.58289468e-04, 5.45679895e-04, 5.41944228e-04, 5.30507026e-04,
       5.23125193e-04, 5.09290043e-04, 4.93967305e-04, 4.75601629e-04,
       4.59394696e-04, 4.52812516e-04, 4.39558529e-04, 4.26949429e-04,
       4.14907621e-04, 4.07139378e-04, 3.99902280e-04, 3.96288548e-04,
       3.86933450e-04, 3.72623799e-04, 3.62443593e-04, 3.54579912e-04,
       3.38415435e-04, 3.29616574e-04, 3.16880863e-04, 3.07011359e-04,
       2.91609975e-04, 2.84735221e-04, 2.74172380e-04, 2.65105542e-04,
       2.57082857e-04, 2.44896369e-04, 2.37787938e-04, 2.29725881e-04,
       2.28237225e-04, 2.26852369e-04, 2.18016571e-04, 2.09597981e-04,
       1.98544338e-04, 1.74896477e-04, 1.63275485e-04, 1.56435191e-04,
       1.48275745e-04, 1.45817565e-04, 1.39375105e-04, 1.25010833e-04,
       1.16516633e-04, 1.08763512e-04, 1.00668042e-04, 9.32800134e-05,
       8.37733596e-05, 7.81804284e-05, 6.89060898e-05, 6.38124700e-05,
       6.20529750e-05, 5.69132679e-05, 4.99048590e-05, 4.85560153e-05,
       4.49553468e-05, 4.31149301e-05, 4.23039470e-05, 3.76702109e-05,
       3.67759864e-05, 3.16512054e-05, 3.01120917e-05, 2.60667672e-05,
       2.04349916e-05, 1.43314337e-05, 1.24786542e-05, 1.17912074e-05,
       8.13427984e-06, 7.14835152e-06, 4.73619419e-06, 4.54880789e-06,
       3.00516288e-06, 2.48700880e-06, 1.42103632e-06, 1.35933926e-32,
       5.66806241e-33, 4.61328068e-33, 4.11195262e-33, 3.67779681e-33,
       3.50738967e-33, 3.14857680e-33, 2.75582387e-33, 2.60463789e-33,
       2.37464161e-33, 2.23370869e-33, 2.15893584e-33, 2.10899758e-33,
       1.94879691e-33, 1.90276693e-33, 1.84531702e-33, 1.81473209e-33,
       1.64465868e-33, 1.58021540e-33, 1.34783065e-33, 1.32212915e-33,
       1.27973095e-33, 1.23499836e-33, 1.21531965e-33, 1.18379429e-33,
       1.10155336e-33, 1.05185273e-33, 9.56909241e-34, 9.07902078e-34,
       8.90870508e-34, 8.54248537e-34, 7.49092956e-34, 6.57276965e-34,
       5.55471963e-34, 5.03439747e-34, 4.58612398e-34, 3.77047795e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 2.66158058e-34,
       2.21697034e-34, 1.63292458e-34, 1.52708221e-34, 1.50066863e-34,
       1.24638560e-34, 1.19580125e-34, 1.08116504e-34, 7.83143261e-35,
       6.73022550e-35, 2.77929680e-35, 8.86548041e-36, 7.53533094e-37])

After looking at the explained variance ratio we can say the last 68 columns are highly correlated to each other.

In [38]:
pca = PCA(n_components= 296)

In [39]:
train_data = pca.fit_transform(train_data)

In [40]:
test_data = pca.transform(test_data)

Action 5: Predicting test data values using XGBoost.

In [41]:
from xgboost import XGBRegressor

In [42]:
regressor = XGBRegressor()

In [43]:
regressor.fit(train_data,x_pred)

C:\Users\91904\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\91904\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \

[11:27:19] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0,
       importance_type='gain', learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=None, subsample=1, verbosity=1)

In [44]:
train_pred = regressor.predict(train_data)

In [45]:
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt

In [46]:
r2_score(train_pred,x_pred)

0.31839851102295713

In [47]:
sqrt(mean_squared_error(train_pred,x_pred))

7.225883797454732

In [48]:
test_pred = regressor.predict(test_data)

In [49]:
test_pred

array([100.63352 , 122.16612 ,  96.491234, ...,  96.19907 , 111.168785,
        97.36724 ], dtype=float32)